# Generated by Django 4.2.3 on 2023-07-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token_user_visit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenuservisit",
            name="hash",
            field=models.CharField(
                help_text="SHA256 hash generated from request properties",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tokenuservisit",
            name="token_key",
            field=models.CharField(
                blank=True, help_text="Auth Token identifier", max_length=64, null=True
            ),
        ),
    ]
