# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from perian.models.account_creation_success import AccountCreationSuccess  # noqa: E501

class TestAccountCreationSuccess(unittest.TestCase):
    """AccountCreationSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountCreationSuccess:
        """Test AccountCreationSuccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountCreationSuccess`
        """
        model = AccountCreationSuccess()  # noqa: E501
        if include_optional:
            return AccountCreationSuccess(
                status = 'success',
                message = 'Account created successful',
                detail = '',
                status_code = 56,
                access_token = ''
            )
        else:
            return AccountCreationSuccess(
                access_token = '',
        )
        """

    def testAccountCreationSuccess(self):
        """Test AccountCreationSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
