
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-26T14:27:13+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5af94df92d7a5d6c3c9c08749ddfa01cf0e9e25",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
