
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-26T11:19:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6fce08abbf8a1a11e219d0b61e3bf90d4e61e269",
 "version": "4.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
