from typing import Final

__LINPG_INTERNAL_IMAGE_PATH: Final[str]

def get_image_location() -> str: ...
def get_database_path() -> str: ...
def get_database() -> dict[str, dict[str, dict[str, bool]]]: ...
