# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chainmaker/protos/config/chainmaker_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0chainmaker/protos/config/chainmaker_server.proto\x12\x06\x63onfig\"\x1a\n\x18\x43hainMakerVersionRequest\"K\n\x19\x43hainMakerVersionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\tBE\n\x18org.chainmaker.pb.configZ)chainmaker.org/chainmaker/pb-go/v3/configb\x06proto3')



_CHAINMAKERVERSIONREQUEST = DESCRIPTOR.message_types_by_name['ChainMakerVersionRequest']
_CHAINMAKERVERSIONRESPONSE = DESCRIPTOR.message_types_by_name['ChainMakerVersionResponse']
ChainMakerVersionRequest = _reflection.GeneratedProtocolMessageType('ChainMakerVersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHAINMAKERVERSIONREQUEST,
  '__module__' : 'chainmaker.protos.config.chainmaker_server_pb2'
  # @@protoc_insertion_point(class_scope:config.ChainMakerVersionRequest)
  })
_sym_db.RegisterMessage(ChainMakerVersionRequest)

ChainMakerVersionResponse = _reflection.GeneratedProtocolMessageType('ChainMakerVersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHAINMAKERVERSIONRESPONSE,
  '__module__' : 'chainmaker.protos.config.chainmaker_server_pb2'
  # @@protoc_insertion_point(class_scope:config.ChainMakerVersionResponse)
  })
_sym_db.RegisterMessage(ChainMakerVersionResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.chainmaker.pb.configZ)chainmaker.org/chainmaker/pb-go/v3/config'
  _CHAINMAKERVERSIONREQUEST._serialized_start=60
  _CHAINMAKERVERSIONREQUEST._serialized_end=86
  _CHAINMAKERVERSIONRESPONSE._serialized_start=88
  _CHAINMAKERVERSIONRESPONSE._serialized_end=163
# @@protoc_insertion_point(module_scope)
