# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: finazon_grpc_python/exchange.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"finazon_grpc_python/exchange.proto\x12\x07\x66inazon\"7\n\x14MarketsCryptoRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"7\n\x19MarketsCryptoResponseItem\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"K\n\x15MarketsCryptoResponse\x12\x32\n\x06result\x18\x01 \x03(\x0b\x32\".finazon.MarketsCryptoResponseItem\"d\n\x14MarketsStocksRequest\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x0c\n\x04page\x18\x04 \x01(\x05\x12\x11\n\tpage_size\x18\x05 \x01(\x05\"G\n\x19MarketsStocksResponseItem\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x0b\n\x03mic\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"K\n\x15MarketsStocksResponse\x12\x32\n\x06result\x18\x01 \x03(\x0b\x32\".finazon.MarketsStocksResponseItem2\xbb\x01\n\x0f\x45xchangeService\x12S\n\x10GetMarketsCrypto\x12\x1d.finazon.MarketsCryptoRequest\x1a\x1e.finazon.MarketsCryptoResponse\"\x00\x12S\n\x10GetMarketsStocks\x12\x1d.finazon.MarketsStocksRequest\x1a\x1e.finazon.MarketsStocksResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finazon_grpc_python.exchange_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MARKETSCRYPTOREQUEST']._serialized_start=47
  _globals['_MARKETSCRYPTOREQUEST']._serialized_end=102
  _globals['_MARKETSCRYPTORESPONSEITEM']._serialized_start=104
  _globals['_MARKETSCRYPTORESPONSEITEM']._serialized_end=159
  _globals['_MARKETSCRYPTORESPONSE']._serialized_start=161
  _globals['_MARKETSCRYPTORESPONSE']._serialized_end=236
  _globals['_MARKETSSTOCKSREQUEST']._serialized_start=238
  _globals['_MARKETSSTOCKSREQUEST']._serialized_end=338
  _globals['_MARKETSSTOCKSRESPONSEITEM']._serialized_start=340
  _globals['_MARKETSSTOCKSRESPONSEITEM']._serialized_end=411
  _globals['_MARKETSSTOCKSRESPONSE']._serialized_start=413
  _globals['_MARKETSSTOCKSRESPONSE']._serialized_end=488
  _globals['_EXCHANGESERVICE']._serialized_start=491
  _globals['_EXCHANGESERVICE']._serialized_end=678
# @@protoc_insertion_point(module_scope)
