from __future__ import annotations
from opendaq.opendaq import ArgumentInfo
from opendaq.opendaq import BaseObject
from opendaq.opendaq import BasicFileLoggerSink
from opendaq.opendaq import BlockReader
from opendaq.opendaq import BlockReaderFromExisting
from opendaq.opendaq import BoolProperty
from opendaq.opendaq import BoolPropertyBuilder
from opendaq.opendaq import Boolean
from opendaq.opendaq import CallableInfo
from opendaq.opendaq import Client
from opendaq.opendaq import Coercer
from opendaq.opendaq import ComplexNumber
from opendaq.opendaq import Component
from opendaq.opendaq import Connection
from opendaq.opendaq import ConstantDataRule
from opendaq.opendaq import Context
from opendaq.opendaq import CoreType
from opendaq.opendaq import DataDescriptor
from opendaq.opendaq import DataDescriptorBuilder
from opendaq.opendaq import DataDescriptorBuilderFromExisting
from opendaq.opendaq import DataDescriptorChangedEventPacket
from opendaq.opendaq import DataPacket
from opendaq.opendaq import DataPacketWithDomain
from opendaq.opendaq import DataRule
from opendaq.opendaq import DataRuleBuilder
from opendaq.opendaq import DataRuleBuilderFromExisting
from opendaq.opendaq import DataRuleType
from opendaq.opendaq import DeviceInfoConfig
from opendaq.opendaq import DeviceType
from opendaq.opendaq import Dict
from opendaq.opendaq import DictProperty
from opendaq.opendaq import DictPropertyBuilder
from opendaq.opendaq import Dimension
from opendaq.opendaq import DimensionBuilder
from opendaq.opendaq import DimensionBuilderFromExisting
from opendaq.opendaq import DimensionRule
from opendaq.opendaq import DimensionRuleBuilder
from opendaq.opendaq import DimensionRuleBuilderFromExisting
from opendaq.opendaq import DimensionRuleType
from opendaq.opendaq import EvalValue
from opendaq.opendaq import EvalValueArgs
from opendaq.opendaq import EvalValueFunc
from opendaq.opendaq import EventArgs
from opendaq.opendaq import EventPacket
from opendaq.opendaq import ExplicitDataRule
from opendaq.opendaq import ExternalAllocator
from opendaq.opendaq import Float
from opendaq.opendaq import FloatProperty
from opendaq.opendaq import FloatPropertyBuilder
from opendaq.opendaq import Folder
from opendaq.opendaq import FolderWithItemType
from opendaq.opendaq import Function
from opendaq.opendaq import FunctionBlockType
from opendaq.opendaq import FunctionProperty
from opendaq.opendaq import FunctionPropertyBuilder
from opendaq.opendaq import IAllocator
from opendaq.opendaq import IArgumentInfo
from opendaq.opendaq import IAwaitable
from opendaq.opendaq import IBaseObject
from opendaq.opendaq import IBlockReader
from opendaq.opendaq import IBoolean
from opendaq.opendaq import ICallableInfo
from opendaq.opendaq import IChannel
from opendaq.opendaq import ICoercer
from opendaq.opendaq import IComplexNumber
from opendaq.opendaq import IComponent
from opendaq.opendaq import IComponentType
from opendaq.opendaq import IConnection
from opendaq.opendaq import IContext
from opendaq.opendaq import IDataDescriptor
from opendaq.opendaq import IDataDescriptorBuilder
from opendaq.opendaq import IDataPacket
from opendaq.opendaq import IDataRule
from opendaq.opendaq import IDataRuleBuilder
from opendaq.opendaq import IDevice
from opendaq.opendaq import IDeviceDomain
from opendaq.opendaq import IDeviceInfo
from opendaq.opendaq import IDeviceInfoConfig
from opendaq.opendaq import IDeviceType
from opendaq.opendaq import IDict
from opendaq.opendaq import IDimension
from opendaq.opendaq import IDimensionBuilder
from opendaq.opendaq import IDimensionRule
from opendaq.opendaq import IDimensionRuleBuilder
from opendaq.opendaq import IEvalValue
from opendaq.opendaq import IEventArgs
from opendaq.opendaq import IEventPacket
from opendaq.opendaq import IFloat
from opendaq.opendaq import IFolder
from opendaq.opendaq import IFolderConfig
from opendaq.opendaq import IFunction
from opendaq.opendaq import IFunctionBlock
from opendaq.opendaq import IFunctionBlockType
from opendaq.opendaq import IGraphVisualization
from opendaq.opendaq import IInputPort
from opendaq.opendaq import IInputPortConfig
from opendaq.opendaq import IInputPortNotifications
from opendaq.opendaq import IInstance
from opendaq.opendaq import IInteger
from opendaq.opendaq import IIterable
from opendaq.opendaq import IIterator
from opendaq.opendaq import IList
from opendaq.opendaq import ILogger
from opendaq.opendaq import ILoggerComponent
from opendaq.opendaq import ILoggerSink
from opendaq.opendaq import ILoggerThreadPool
from opendaq.opendaq import IModule
from opendaq.opendaq import IModuleManager
from opendaq.opendaq import IOwnable
from opendaq.opendaq import IPacket
from opendaq.opendaq import IPacketDestructCallback
from opendaq.opendaq import IPacketReader
from opendaq.opendaq import IProcedure
from opendaq.opendaq import IProperty
from opendaq.opendaq import IPropertyBuilder
from opendaq.opendaq import IPropertyObject
from opendaq.opendaq import IPropertyObjectClass
from opendaq.opendaq import IPropertyObjectClassBuilder
from opendaq.opendaq import IPropertyObjectProtected
from opendaq.opendaq import IPropertyValueEventArgs
from opendaq.opendaq import IRange
from opendaq.opendaq import IRatio
from opendaq.opendaq import IReader
from opendaq.opendaq import IRemovable
from opendaq.opendaq import ISampleReader
from opendaq.opendaq import IScaling
from opendaq.opendaq import IScalingBuilder
from opendaq.opendaq import IScheduler
from opendaq.opendaq import IServer
from opendaq.opendaq import IServerType
from opendaq.opendaq import ISignal
from opendaq.opendaq import ISignalConfig
from opendaq.opendaq import ISignalEvents
from opendaq.opendaq import ISignalRemote
from opendaq.opendaq import ISimpleType
from opendaq.opendaq import IStreamReader
from opendaq.opendaq import IStreaming
from opendaq.opendaq import IStreamingInfo
from opendaq.opendaq import IStreamingInfoConfig
from opendaq.opendaq import IString
from opendaq.opendaq import IStruct
from opendaq.opendaq import IStructType
from opendaq.opendaq import ITags
from opendaq.opendaq import ITagsConfig
from opendaq.opendaq import ITailReader
from opendaq.opendaq import ITask
from opendaq.opendaq import ITaskGraph
from opendaq.opendaq import IType
from opendaq.opendaq import ITypeManager
from opendaq.opendaq import IUnit
from opendaq.opendaq import IUnitBuilder
from opendaq.opendaq import IValidator
from opendaq.opendaq import InputPort
from opendaq.opendaq import IntProperty
from opendaq.opendaq import IntPropertyBuilder
from opendaq.opendaq import Integer
from opendaq.opendaq import IoFolder
from opendaq.opendaq import LinearDataRule
from opendaq.opendaq import LinearDimensionRule
from opendaq.opendaq import LinearScaling
from opendaq.opendaq import List
from opendaq.opendaq import ListDimensionRule
from opendaq.opendaq import ListProperty
from opendaq.opendaq import ListPropertyBuilder
from opendaq.opendaq import LogLevel
from opendaq.opendaq import LogarithmicDimensionRule
from opendaq.opendaq import Logger
from opendaq.opendaq import LoggerComponent
from opendaq.opendaq import LoggerThreadPool
from opendaq.opendaq import MallocAllocator
from opendaq.opendaq import ModuleManager
from opendaq.opendaq import ObjectProperty
from opendaq.opendaq import ObjectPropertyBuilder
from opendaq.opendaq import PacketReader
from opendaq.opendaq import PacketReadyNotification
from opendaq.opendaq import PacketType
from opendaq.opendaq import Procedure
from opendaq.opendaq import PropertyBuilder
from opendaq.opendaq import PropertyChangedEventPacket
from opendaq.opendaq import PropertyEventType
from opendaq.opendaq import PropertyFromBuildParams
from opendaq.opendaq import PropertyObject
from opendaq.opendaq import PropertyObjectClassBuilder
from opendaq.opendaq import PropertyObjectClassBuilderWithManager
from opendaq.opendaq import PropertyObjectClassFromBuildParams
from opendaq.opendaq import PropertyObjectWithClassAndManager
from opendaq.opendaq import PropertyValueEventArgs
from opendaq.opendaq import Range
from opendaq.opendaq import Ratio
from opendaq.opendaq import RatioProperty
from opendaq.opendaq import RatioPropertyBuilder
from opendaq.opendaq import ReadMode
from opendaq.opendaq import ReadTimeoutType
from opendaq.opendaq import ReferenceProperty
from opendaq.opendaq import ReferencePropertyBuilder
from opendaq.opendaq import RotatingFileLoggerSink
from opendaq.opendaq import Scaling
from opendaq.opendaq import ScalingBuilder
from opendaq.opendaq import ScalingBuilderFromExisting
from opendaq.opendaq import ScalingType
from opendaq.opendaq import Scheduler
from opendaq.opendaq import SelectionProperty
from opendaq.opendaq import SelectionPropertyBuilder
from opendaq.opendaq import ServerType
from opendaq.opendaq import Signal
from opendaq.opendaq import SignalWithDescriptor
from opendaq.opendaq import SimpleType
from opendaq.opendaq import SparseSelectionProperty
from opendaq.opendaq import SparseSelectionPropertyBuilder
from opendaq.opendaq import StdErrLoggerSink
from opendaq.opendaq import StdOutLoggerSink
from opendaq.opendaq import StreamReader
from opendaq.opendaq import StreamReaderFromExisting
from opendaq.opendaq import StreamingInfoConfig
from opendaq.opendaq import String
from opendaq.opendaq import StringProperty
from opendaq.opendaq import StringPropertyBuilder
from opendaq.opendaq import Struct
from opendaq.opendaq import StructProperty
from opendaq.opendaq import StructPropertyBuilder
from opendaq.opendaq import StructType
from opendaq.opendaq import StructTypeNoDefaults
from opendaq.opendaq import Tags
from opendaq.opendaq import TagsFromExisting
from opendaq.opendaq import TailReader
from opendaq.opendaq import TailReaderFromExisting
from opendaq.opendaq import Task
from opendaq.opendaq import TaskGraph
from opendaq.opendaq import TypeManager
from opendaq.opendaq import Unit
from opendaq.opendaq import UnitBuilder
from opendaq.opendaq import UnitBuilderFromExisting
from opendaq.opendaq import Validator
from opendaq.opendaq import clear_error_info
from opendaq.opendaq import get_tracked_object_count
from opendaq.opendaq import print_tracked_objects
import os as os
from . import opendaq
__all__ = ['ArgumentInfo', 'BaseObject', 'BasicFileLoggerSink', 'BlockReader', 'BlockReaderFromExisting', 'BoolProperty', 'BoolPropertyBuilder', 'Boolean', 'CallableInfo', 'Client', 'Coercer', 'ComplexNumber', 'Component', 'Connection', 'ConstantDataRule', 'Context', 'CoreType', 'DataDescriptor', 'DataDescriptorBuilder', 'DataDescriptorBuilderFromExisting', 'DataDescriptorChangedEventPacket', 'DataPacket', 'DataPacketWithDomain', 'DataRule', 'DataRuleBuilder', 'DataRuleBuilderFromExisting', 'DataRuleType', 'DeviceInfoConfig', 'DeviceType', 'Dict', 'DictProperty', 'DictPropertyBuilder', 'Dimension', 'DimensionBuilder', 'DimensionBuilderFromExisting', 'DimensionRule', 'DimensionRuleBuilder', 'DimensionRuleBuilderFromExisting', 'DimensionRuleType', 'EvalValue', 'EvalValueArgs', 'EvalValueFunc', 'EventArgs', 'EventPacket', 'ExplicitDataRule', 'ExternalAllocator', 'Float', 'FloatProperty', 'FloatPropertyBuilder', 'Folder', 'FolderWithItemType', 'Function', 'FunctionBlockType', 'FunctionProperty', 'FunctionPropertyBuilder', 'IAllocator', 'IArgumentInfo', 'IAwaitable', 'IBaseObject', 'IBlockReader', 'IBoolean', 'ICallableInfo', 'IChannel', 'ICoercer', 'IComplexNumber', 'IComponent', 'IComponentType', 'IConnection', 'IContext', 'IDataDescriptor', 'IDataDescriptorBuilder', 'IDataPacket', 'IDataRule', 'IDataRuleBuilder', 'IDevice', 'IDeviceDomain', 'IDeviceInfo', 'IDeviceInfoConfig', 'IDeviceType', 'IDict', 'IDimension', 'IDimensionBuilder', 'IDimensionRule', 'IDimensionRuleBuilder', 'IEvalValue', 'IEventArgs', 'IEventPacket', 'IFloat', 'IFolder', 'IFolderConfig', 'IFunction', 'IFunctionBlock', 'IFunctionBlockType', 'IGraphVisualization', 'IInputPort', 'IInputPortConfig', 'IInputPortNotifications', 'IInstance', 'IInteger', 'IIterable', 'IIterator', 'IList', 'ILogger', 'ILoggerComponent', 'ILoggerSink', 'ILoggerThreadPool', 'IModule', 'IModuleManager', 'IOwnable', 'IPacket', 'IPacketDestructCallback', 'IPacketReader', 'IProcedure', 'IProperty', 'IPropertyBuilder', 'IPropertyObject', 'IPropertyObjectClass', 'IPropertyObjectClassBuilder', 'IPropertyObjectProtected', 'IPropertyValueEventArgs', 'IRange', 'IRatio', 'IReader', 'IRemovable', 'ISampleReader', 'IScaling', 'IScalingBuilder', 'IScheduler', 'IServer', 'IServerType', 'ISignal', 'ISignalConfig', 'ISignalEvents', 'ISignalRemote', 'ISimpleType', 'IStreamReader', 'IStreaming', 'IStreamingInfo', 'IStreamingInfoConfig', 'IString', 'IStruct', 'IStructType', 'ITags', 'ITagsConfig', 'ITailReader', 'ITask', 'ITaskGraph', 'IType', 'ITypeManager', 'IUnit', 'IUnitBuilder', 'IValidator', 'InputPort', 'Instance', 'IntProperty', 'IntPropertyBuilder', 'Integer', 'IoFolder', 'LinearDataRule', 'LinearDimensionRule', 'LinearScaling', 'List', 'ListDimensionRule', 'ListProperty', 'ListPropertyBuilder', 'LogLevel', 'LogarithmicDimensionRule', 'Logger', 'LoggerComponent', 'LoggerThreadPool', 'MallocAllocator', 'ModuleManager', 'OPENDAQ_MODULES_DIR', 'ObjectProperty', 'ObjectPropertyBuilder', 'PacketReader', 'PacketReadyNotification', 'PacketType', 'Procedure', 'PropertyBuilder', 'PropertyChangedEventPacket', 'PropertyEventType', 'PropertyFromBuildParams', 'PropertyObject', 'PropertyObjectClassBuilder', 'PropertyObjectClassBuilderWithManager', 'PropertyObjectClassFromBuildParams', 'PropertyObjectWithClassAndManager', 'PropertyValueEventArgs', 'Range', 'Ratio', 'RatioProperty', 'RatioPropertyBuilder', 'ReadMode', 'ReadTimeoutType', 'ReferenceProperty', 'ReferencePropertyBuilder', 'RotatingFileLoggerSink', 'Scaling', 'ScalingBuilder', 'ScalingBuilderFromExisting', 'ScalingType', 'Scheduler', 'SelectionProperty', 'SelectionPropertyBuilder', 'ServerType', 'Signal', 'SignalWithDescriptor', 'SimpleType', 'SparseSelectionProperty', 'SparseSelectionPropertyBuilder', 'StdErrLoggerSink', 'StdOutLoggerSink', 'StreamReader', 'StreamReaderFromExisting', 'StreamingInfoConfig', 'String', 'StringProperty', 'StringPropertyBuilder', 'Struct', 'StructProperty', 'StructPropertyBuilder', 'StructType', 'StructTypeNoDefaults', 'Tags', 'TagsFromExisting', 'TailReader', 'TailReaderFromExisting', 'Task', 'TaskGraph', 'TypeManager', 'Unit', 'UnitBuilder', 'UnitBuilderFromExisting', 'Validator', 'clear_error_info', 'get_tracked_object_count', 'opendaq', 'os', 'print_tracked_objects']
def Instance(*args) -> opendaq.IInstance:
    ...
OPENDAQ_MODULES_DIR: str = '/__w/openDAQ/openDAQ/build/pip/packages/opendaq'
