from enum import Enum


class BiddingZonesEnum(str, Enum):
    DK1 = "DK1"
    DK1_SB = "DK1_SB"
    DK1_CO = "DK1_CO"
    DK1_DE = "DK1_DE"
    DK1_KS = "DK1_KS"
    DK1_SK = "DK1_SK"
    DK1_ST = "DK1_ST"
    DK2_SB = "DK2_SB"
    DK2_KO = "DK2_KO"
    DK2_ST = "DK2_ST"
    DK2 = "DK2"
    FI = "FI"
    FI_EL = "FI_EL"
    FI_FS = "FI_FS"
    NO1 = "NO1"
    NO2 = "NO2"
    NO2_ND = "NO2_ND"
    NO2_SK = "NO2_SK"
    NO2_NK = "NO2_NK"
    NO3 = "NO3"
    NO4 = "NO4"
    NO5 = "NO5"
    SE1 = "SE1"
    SE2 = "SE2"
    SE3 = "SE3"
    SE3_FS = "SE3_FS"
    SE3_KS = "SE3_KS"
    SE3_SWL = "SE3_SWL"
    SE4 = "SE4"
    SE4_BC = "SE4_BC"
    SE4_NB = "SE4_NB"
    SE4_SP = "SE4_SP"
    SE4_SWL = "SE4_SWL"
