# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr
from perian.models.api_models_memory import ApiModelsMemory
from perian.models.gpu_vendor import GpuVendor

class RegisteredGPU(BaseModel):
    """
    RegisteredGPU
    """
    name: StrictStr = Field(...)
    name_short: StrictStr = Field(...)
    vendor: GpuVendor = Field(...)
    memory: ApiModelsMemory = Field(...)
    __properties = ["name", "name_short", "vendor", "memory"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RegisteredGPU:
        """Create an instance of RegisteredGPU from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of memory
        if self.memory:
            _dict['memory'] = self.memory.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RegisteredGPU:
        """Create an instance of RegisteredGPU from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RegisteredGPU.parse_obj(obj)

        _obj = RegisteredGPU.parse_obj({
            "name": obj.get("name"),
            "name_short": obj.get("name_short"),
            "vendor": obj.get("vendor"),
            "memory": ApiModelsMemory.from_dict(obj.get("memory")) if obj.get("memory") is not None else None
        })
        return _obj


