# coding: utf-8

"""
    42videobricks

    42videobricks is a Video Platform As A Service (VPaaS)

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class VideoMultipartUploadInitResponsePartsInner(BaseModel):
    """
    part signed url object  # noqa: E501
    """
    signed_url: Optional[StrictStr] = Field(None, alias="signedUrl", description="part signed url")
    part_number: Optional[StrictInt] = Field(None, alias="PartNumber", description="part number")
    __properties = ["signedUrl", "PartNumber"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VideoMultipartUploadInitResponsePartsInner:
        """Create an instance of VideoMultipartUploadInitResponsePartsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VideoMultipartUploadInitResponsePartsInner:
        """Create an instance of VideoMultipartUploadInitResponsePartsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VideoMultipartUploadInitResponsePartsInner.parse_obj(obj)

        _obj = VideoMultipartUploadInitResponsePartsInner.parse_obj({
            "signed_url": obj.get("signedUrl"),
            "part_number": obj.get("PartNumber")
        })
        return _obj


