
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-27T09:05:26-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf25e07d9701bf8e9e51bfe76d428e5c1be1afda",
 "version": "2.23.0rc5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
