
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-26T17:12:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3efa0219d0092a2fba9db92636698388d42a278a",
 "version": "2.14.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
