
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-26T18:13:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e12b21703494dcbb8f7aa951b40ebe1d033307ba",
 "version": "0.25.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
