# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chainmaker/protos/syscontract/ethereum.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,chainmaker/protos/syscontract/ethereum.proto\x12\x0bsyscontract\"(\n\x0c\x45thBalanceOf\"\x18\n\tParameter\x12\x0b\n\x07\x41\x43\x43OUNT\x10\x00\"$\n\x08\x45thNonce\"\x18\n\tParameter\x12\x0b\n\x07\x41\x43\x43OUNT\x10\x00\".\n\x0b\x45thTransfer\"\x1f\n\tParameter\x12\x06\n\x02TO\x10\x00\x12\n\n\x06\x41MOUNT\x10\x01\"/\n\x07\x45thMint\"$\n\tParameter\x12\x0b\n\x07\x41\x43\x43OUNT\x10\x00\x12\n\n\x06\x41MOUNT\x10\x01\"1\n\x0b\x45thRegister\"\"\n\tParameter\x12\x0b\n\x07\x41\x43\x43OUNT\x10\x00\x12\x08\n\x04NAME\x10\x01\")\n\rEthUnregister\"\x18\n\tParameter\x12\x0b\n\x07\x41\x43\x43OUNT\x10\x00\")\n\rEthGetAccount\"\x18\n\tParameter\x12\x0b\n\x07\x41\x43\x43OUNT\x10\x00\"\\\n\x0e\x45thEstimateGas\"J\n\tParameter\x12\x08\n\x04\x46ROM\x10\x00\x12\x06\n\x02TO\x10\x01\x12\t\n\x05VALUE\x10\x02\x12\x08\n\x04\x44\x41TA\x10\x03\x12\x07\n\x03GAS\x10\x04\x12\r\n\tGAS_PRICE\x10\x05\"U\n\x07\x45thCall\"J\n\tParameter\x12\x08\n\x04\x46ROM\x10\x00\x12\x06\n\x02TO\x10\x01\x12\t\n\x05VALUE\x10\x02\x12\x08\n\x04\x44\x41TA\x10\x03\x12\x07\n\x03GAS\x10\x04\x12\r\n\tGAS_PRICE\x10\x05*\xe2\x01\n\x10\x45thereumFunction\x12\x08\n\x04Name\x10\x00\x12\n\n\x06Symbol\x10\x01\x12\x0c\n\x08\x44\x65\x63imals\x10\x02\x12\x0f\n\x0bTotalSupply\x10\x03\x12\r\n\tBalanceOf\x10\x04\x12\t\n\x05Nonce\x10\x05\x12\x0c\n\x08Transfer\x10\x06\x12\x08\n\x04Mint\x10\x07\x12\n\n\x06Unpack\x10\x08\x12\x0c\n\x08Register\x10\t\x12\x0e\n\nUnregister\x10\n\x12\x0e\n\nGetAccount\x10\x0b\x12\x12\n\x0eGetAccountList\x10\x0c\x12\x0f\n\x0b\x45stimateGas\x10\r\x12\x08\n\x04\x43\x61ll\x10\x0e\x42O\n\x1dorg.chainmaker.pb.syscontractZ.chainmaker.org/chainmaker/pb-go/v3/syscontractb\x06proto3')

_ETHEREUMFUNCTION = DESCRIPTOR.enum_types_by_name['EthereumFunction']
EthereumFunction = enum_type_wrapper.EnumTypeWrapper(_ETHEREUMFUNCTION)
Name = 0
Symbol = 1
Decimals = 2
TotalSupply = 3
BalanceOf = 4
Nonce = 5
Transfer = 6
Mint = 7
Unpack = 8
Register = 9
Unregister = 10
GetAccount = 11
GetAccountList = 12
EstimateGas = 13
Call = 14


_ETHBALANCEOF = DESCRIPTOR.message_types_by_name['EthBalanceOf']
_ETHNONCE = DESCRIPTOR.message_types_by_name['EthNonce']
_ETHTRANSFER = DESCRIPTOR.message_types_by_name['EthTransfer']
_ETHMINT = DESCRIPTOR.message_types_by_name['EthMint']
_ETHREGISTER = DESCRIPTOR.message_types_by_name['EthRegister']
_ETHUNREGISTER = DESCRIPTOR.message_types_by_name['EthUnregister']
_ETHGETACCOUNT = DESCRIPTOR.message_types_by_name['EthGetAccount']
_ETHESTIMATEGAS = DESCRIPTOR.message_types_by_name['EthEstimateGas']
_ETHCALL = DESCRIPTOR.message_types_by_name['EthCall']
_ETHBALANCEOF_PARAMETER = _ETHBALANCEOF.enum_types_by_name['Parameter']
_ETHNONCE_PARAMETER = _ETHNONCE.enum_types_by_name['Parameter']
_ETHTRANSFER_PARAMETER = _ETHTRANSFER.enum_types_by_name['Parameter']
_ETHMINT_PARAMETER = _ETHMINT.enum_types_by_name['Parameter']
_ETHREGISTER_PARAMETER = _ETHREGISTER.enum_types_by_name['Parameter']
_ETHUNREGISTER_PARAMETER = _ETHUNREGISTER.enum_types_by_name['Parameter']
_ETHGETACCOUNT_PARAMETER = _ETHGETACCOUNT.enum_types_by_name['Parameter']
_ETHESTIMATEGAS_PARAMETER = _ETHESTIMATEGAS.enum_types_by_name['Parameter']
_ETHCALL_PARAMETER = _ETHCALL.enum_types_by_name['Parameter']
EthBalanceOf = _reflection.GeneratedProtocolMessageType('EthBalanceOf', (_message.Message,), {
  'DESCRIPTOR' : _ETHBALANCEOF,
  '__module__' : 'chainmaker.protos.syscontract.ethereum_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.EthBalanceOf)
  })
_sym_db.RegisterMessage(EthBalanceOf)

EthNonce = _reflection.GeneratedProtocolMessageType('EthNonce', (_message.Message,), {
  'DESCRIPTOR' : _ETHNONCE,
  '__module__' : 'chainmaker.protos.syscontract.ethereum_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.EthNonce)
  })
_sym_db.RegisterMessage(EthNonce)

EthTransfer = _reflection.GeneratedProtocolMessageType('EthTransfer', (_message.Message,), {
  'DESCRIPTOR' : _ETHTRANSFER,
  '__module__' : 'chainmaker.protos.syscontract.ethereum_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.EthTransfer)
  })
_sym_db.RegisterMessage(EthTransfer)

EthMint = _reflection.GeneratedProtocolMessageType('EthMint', (_message.Message,), {
  'DESCRIPTOR' : _ETHMINT,
  '__module__' : 'chainmaker.protos.syscontract.ethereum_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.EthMint)
  })
_sym_db.RegisterMessage(EthMint)

EthRegister = _reflection.GeneratedProtocolMessageType('EthRegister', (_message.Message,), {
  'DESCRIPTOR' : _ETHREGISTER,
  '__module__' : 'chainmaker.protos.syscontract.ethereum_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.EthRegister)
  })
_sym_db.RegisterMessage(EthRegister)

EthUnregister = _reflection.GeneratedProtocolMessageType('EthUnregister', (_message.Message,), {
  'DESCRIPTOR' : _ETHUNREGISTER,
  '__module__' : 'chainmaker.protos.syscontract.ethereum_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.EthUnregister)
  })
_sym_db.RegisterMessage(EthUnregister)

EthGetAccount = _reflection.GeneratedProtocolMessageType('EthGetAccount', (_message.Message,), {
  'DESCRIPTOR' : _ETHGETACCOUNT,
  '__module__' : 'chainmaker.protos.syscontract.ethereum_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.EthGetAccount)
  })
_sym_db.RegisterMessage(EthGetAccount)

EthEstimateGas = _reflection.GeneratedProtocolMessageType('EthEstimateGas', (_message.Message,), {
  'DESCRIPTOR' : _ETHESTIMATEGAS,
  '__module__' : 'chainmaker.protos.syscontract.ethereum_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.EthEstimateGas)
  })
_sym_db.RegisterMessage(EthEstimateGas)

EthCall = _reflection.GeneratedProtocolMessageType('EthCall', (_message.Message,), {
  'DESCRIPTOR' : _ETHCALL,
  '__module__' : 'chainmaker.protos.syscontract.ethereum_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.EthCall)
  })
_sym_db.RegisterMessage(EthCall)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035org.chainmaker.pb.syscontractZ.chainmaker.org/chainmaker/pb-go/v3/syscontract'
  _ETHEREUMFUNCTION._serialized_start=557
  _ETHEREUMFUNCTION._serialized_end=783
  _ETHBALANCEOF._serialized_start=61
  _ETHBALANCEOF._serialized_end=101
  _ETHBALANCEOF_PARAMETER._serialized_start=77
  _ETHBALANCEOF_PARAMETER._serialized_end=101
  _ETHNONCE._serialized_start=103
  _ETHNONCE._serialized_end=139
  _ETHNONCE_PARAMETER._serialized_start=77
  _ETHNONCE_PARAMETER._serialized_end=101
  _ETHTRANSFER._serialized_start=141
  _ETHTRANSFER._serialized_end=187
  _ETHTRANSFER_PARAMETER._serialized_start=156
  _ETHTRANSFER_PARAMETER._serialized_end=187
  _ETHMINT._serialized_start=189
  _ETHMINT._serialized_end=236
  _ETHMINT_PARAMETER._serialized_start=200
  _ETHMINT_PARAMETER._serialized_end=236
  _ETHREGISTER._serialized_start=238
  _ETHREGISTER._serialized_end=287
  _ETHREGISTER_PARAMETER._serialized_start=253
  _ETHREGISTER_PARAMETER._serialized_end=287
  _ETHUNREGISTER._serialized_start=289
  _ETHUNREGISTER._serialized_end=330
  _ETHUNREGISTER_PARAMETER._serialized_start=77
  _ETHUNREGISTER_PARAMETER._serialized_end=101
  _ETHGETACCOUNT._serialized_start=332
  _ETHGETACCOUNT._serialized_end=373
  _ETHGETACCOUNT_PARAMETER._serialized_start=77
  _ETHGETACCOUNT_PARAMETER._serialized_end=101
  _ETHESTIMATEGAS._serialized_start=375
  _ETHESTIMATEGAS._serialized_end=467
  _ETHESTIMATEGAS_PARAMETER._serialized_start=393
  _ETHESTIMATEGAS_PARAMETER._serialized_end=467
  _ETHCALL._serialized_start=469
  _ETHCALL._serialized_end=554
  _ETHCALL_PARAMETER._serialized_start=393
  _ETHCALL_PARAMETER._serialized_end=467
# @@protoc_insertion_point(module_scope)
