# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chainmaker/protos/syscontract/store_hot_cold_data_separate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@chainmaker/protos/syscontract/store_hot_cold_data_separate.proto\x12\x0bsyscontract\"L\n\x1b\x44oHotColdDataSeparateHeight\"-\n\tParameter\x12\x10\n\x0cSTART_HEIGHT\x10\x00\x12\x0e\n\nEND_HEIGHT\x10\x01\"4\n\x19GetHotColdDataSeparateJob\"\x17\n\tParameter\x12\n\n\x06JOB_ID\x10\x00*\x86\x01\n\x1bHotColdDataSeparateFunction\x12\x1b\n\x17\x44oHotColdDataSeparation\x10\x00\x12#\n\x1fGetHotColdDataSeparationJobByID\x10\x01\x12%\n!GetHotColdDataSeparationMaxHeight\x10\x02\x42O\n\x1dorg.chainmaker.pb.syscontractZ.chainmaker.org/chainmaker/pb-go/v3/syscontractb\x06proto3')

_HOTCOLDDATASEPARATEFUNCTION = DESCRIPTOR.enum_types_by_name['HotColdDataSeparateFunction']
HotColdDataSeparateFunction = enum_type_wrapper.EnumTypeWrapper(_HOTCOLDDATASEPARATEFUNCTION)
DoHotColdDataSeparation = 0
GetHotColdDataSeparationJobByID = 1
GetHotColdDataSeparationMaxHeight = 2


_DOHOTCOLDDATASEPARATEHEIGHT = DESCRIPTOR.message_types_by_name['DoHotColdDataSeparateHeight']
_GETHOTCOLDDATASEPARATEJOB = DESCRIPTOR.message_types_by_name['GetHotColdDataSeparateJob']
_DOHOTCOLDDATASEPARATEHEIGHT_PARAMETER = _DOHOTCOLDDATASEPARATEHEIGHT.enum_types_by_name['Parameter']
_GETHOTCOLDDATASEPARATEJOB_PARAMETER = _GETHOTCOLDDATASEPARATEJOB.enum_types_by_name['Parameter']
DoHotColdDataSeparateHeight = _reflection.GeneratedProtocolMessageType('DoHotColdDataSeparateHeight', (_message.Message,), {
  'DESCRIPTOR' : _DOHOTCOLDDATASEPARATEHEIGHT,
  '__module__' : 'chainmaker.protos.syscontract.store_hot_cold_data_separate_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.DoHotColdDataSeparateHeight)
  })
_sym_db.RegisterMessage(DoHotColdDataSeparateHeight)

GetHotColdDataSeparateJob = _reflection.GeneratedProtocolMessageType('GetHotColdDataSeparateJob', (_message.Message,), {
  'DESCRIPTOR' : _GETHOTCOLDDATASEPARATEJOB,
  '__module__' : 'chainmaker.protos.syscontract.store_hot_cold_data_separate_pb2'
  # @@protoc_insertion_point(class_scope:syscontract.GetHotColdDataSeparateJob)
  })
_sym_db.RegisterMessage(GetHotColdDataSeparateJob)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035org.chainmaker.pb.syscontractZ.chainmaker.org/chainmaker/pb-go/v3/syscontract'
  _HOTCOLDDATASEPARATEFUNCTION._serialized_start=214
  _HOTCOLDDATASEPARATEFUNCTION._serialized_end=348
  _DOHOTCOLDDATASEPARATEHEIGHT._serialized_start=81
  _DOHOTCOLDDATASEPARATEHEIGHT._serialized_end=157
  _DOHOTCOLDDATASEPARATEHEIGHT_PARAMETER._serialized_start=112
  _DOHOTCOLDDATASEPARATEHEIGHT_PARAMETER._serialized_end=157
  _GETHOTCOLDDATASEPARATEJOB._serialized_start=159
  _GETHOTCOLDDATASEPARATEJOB._serialized_end=211
  _GETHOTCOLDDATASEPARATEJOB_PARAMETER._serialized_start=188
  _GETHOTCOLDDATASEPARATEJOB_PARAMETER._serialized_end=211
# @@protoc_insertion_point(module_scope)
