# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import standardbots.auto_generated.openapi_client
from standardbots.auto_generated.openapi_client.paths.api_v1_configuration_control_mode import post  # noqa: E501
from standardbots.auto_generated.openapi_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiV1ConfigurationControlMode(ApiTestMixin, unittest.TestCase):
    """
    ApiV1ConfigurationControlMode unit test stubs
        Set Control Mode  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
