
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-26T14:25:16+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2d6bae905f6f5ec5eb6389abcf1a05e62b7bcdd",
 "version": "2.23.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
