"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergePythonSDK.crm
from MergePythonSDK.crm.api.engagement_types_api import EngagementTypesApi  # noqa: E501


class TestEngagementTypesApi(unittest.TestCase):
    """EngagementTypesApi unit test stubs"""

    def setUp(self):
        self.api = EngagementTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_engagement_types_list(self):
        """Test case for engagement_types_list

        """
        pass

    def test_engagement_types_remote_field_classes_list(self):
        """Test case for engagement_types_remote_field_classes_list

        """
        pass

    def test_engagement_types_retrieve(self):
        """Test case for engagement_types_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
