"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.crm
from MergePythonSDK.crm.model.cardinality_enum import CardinalityEnum
from MergePythonSDK.crm.model.object_class_description_request import ObjectClassDescriptionRequest
globals()['CardinalityEnum'] = CardinalityEnum
globals()['ObjectClassDescriptionRequest'] = ObjectClassDescriptionRequest
from MergePythonSDK.crm.model.association_type_request_request import AssociationTypeRequestRequest
from MergePythonSDK.shared.api_client import ApiClient


class TestAssociationTypeRequestRequest(unittest.TestCase):
    """AssociationTypeRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssociationTypeRequestRequest(self):
        """Test AssociationTypeRequestRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssociationTypeRequestRequest()  # noqa: E501

        """
        No test json responses were defined for AssociationTypeRequestRequest
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (AssociationTypeRequestRequest,), False)

        assert deserialized is not None

        assert deserialized.source_object_class is not None
        assert deserialized.target_object_classes is not None
        assert deserialized.remote_key_name is not None


if __name__ == '__main__':
    unittest.main()
