"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.crm
from MergePythonSDK.crm.model.issue_status_enum import IssueStatusEnum
from MergePythonSDK.shared.api_client import ApiClient


class TestIssueStatusEnum(unittest.TestCase):
    """IssueStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssueStatusEnum(self):
        """Test IssueStatusEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IssueStatusEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
