"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergePythonSDK.crm
from MergePythonSDK.crm.api.custom_object_classes_api import CustomObjectClassesApi  # noqa: E501


class TestCustomObjectClassesApi(unittest.TestCase):
    """CustomObjectClassesApi unit test stubs"""

    def setUp(self):
        self.api = CustomObjectClassesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_custom_object_classes_generator_update(self):
        """Test case for custom_object_classes_generator_update

        """
        pass

    def test_custom_object_classes_list(self):
        """Test case for custom_object_classes_list

        """
        pass

    def test_custom_object_classes_retrieve(self):
        """Test case for custom_object_classes_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
