"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.crm
from MergePythonSDK.shared.model.remote_data import RemoteData
from MergePythonSDK.crm.model.remote_field import RemoteField
globals()['RemoteData'] = RemoteData
globals()['RemoteField'] = RemoteField
from MergePythonSDK.crm.model.note import Note
from MergePythonSDK.shared.api_client import ApiClient


class TestNote(unittest.TestCase):
    """Note unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNote(self):
        """Test Note"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Note()  # noqa: E501

        """
        No test json responses were defined for Note
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (Note,), False)

        assert deserialized is not None



if __name__ == '__main__':
    unittest.main()
