"""
    Merge CRM API

    The unified API for building rich integrations with multiple CRM platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.crm
from MergePythonSDK.crm.model.association_type import AssociationType
from MergePythonSDK.crm.model.debug_mode_log import DebugModeLog
from MergePythonSDK.crm.model.error_validation_problem import ErrorValidationProblem
from MergePythonSDK.crm.model.warning_validation_problem import WarningValidationProblem
globals()['AssociationType'] = AssociationType
globals()['DebugModeLog'] = DebugModeLog
globals()['ErrorValidationProblem'] = ErrorValidationProblem
globals()['WarningValidationProblem'] = WarningValidationProblem
from MergePythonSDK.crm.model.crm_association_type_response import CRMAssociationTypeResponse
from MergePythonSDK.shared.api_client import ApiClient


class TestCRMAssociationTypeResponse(unittest.TestCase):
    """CRMAssociationTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCRMAssociationTypeResponse(self):
        """Test CRMAssociationTypeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CRMAssociationTypeResponse()  # noqa: E501

        """
        No test json responses were defined for CRMAssociationTypeResponse
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (CRMAssociationTypeResponse,), False)

        assert deserialized is not None

        assert deserialized.model is not None
        assert deserialized.warnings is not None
        assert deserialized.errors is not None


if __name__ == '__main__':
    unittest.main()
