# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chainmaker/protos/common/transaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chainmaker.protos.common import request_pb2 as chainmaker_dot_protos_dot_common_dot_request__pb2
from chainmaker.protos.common import result_pb2 as chainmaker_dot_protos_dot_common_dot_result__pb2
from chainmaker.protos.common import rwset_pb2 as chainmaker_dot_protos_dot_common_dot_rwset__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*chainmaker/protos/common/transaction.proto\x12\x06\x63ommon\x1a&chainmaker/protos/common/request.proto\x1a%chainmaker/protos/common/result.proto\x1a$chainmaker/protos/common/rwset.proto\"\xcf\x01\n\x0bTransaction\x12 \n\x07payload\x18\x01 \x01(\x0b\x32\x0f.common.Payload\x12(\n\x06sender\x18\x02 \x01(\x0b\x32\x18.common.EndorsementEntry\x12+\n\tendorsers\x18\x03 \x03(\x0b\x32\x18.common.EndorsementEntry\x12\x1e\n\x06result\x18\x04 \x01(\x0b\x32\x0e.common.Result\x12\'\n\x05payer\x18\x05 \x01(\x0b\x32\x18.common.EndorsementEntry\"\x90\x01\n\x0fTransactionInfo\x12(\n\x0btransaction\x18\x01 \x01(\x0b\x32\x13.common.Transaction\x12\x14\n\x0c\x62lock_height\x18\x02 \x01(\x04\x12\x12\n\nblock_hash\x18\x03 \x01(\x0c\x12\x10\n\x08tx_index\x18\x04 \x01(\r\x12\x17\n\x0f\x62lock_timestamp\x18\x05 \x01(\x03\"a\n\x14TransactionWithRWSet\x12(\n\x0btransaction\x18\x01 \x01(\x0b\x32\x13.common.Transaction\x12\x1f\n\x06rw_set\x18\x02 \x01(\x0b\x32\x0f.common.TxRWSet\"\xba\x01\n\x18TransactionInfoWithRWSet\x12(\n\x0btransaction\x18\x01 \x01(\x0b\x32\x13.common.Transaction\x12\x14\n\x0c\x62lock_height\x18\x02 \x01(\x04\x12\x12\n\nblock_hash\x18\x03 \x01(\x0c\x12\x10\n\x08tx_index\x18\x04 \x01(\r\x12\x17\n\x0f\x62lock_timestamp\x18\x05 \x01(\x03\x12\x1f\n\x06rw_set\x18\x06 \x01(\x0b\x32\x0f.common.TxRWSetB\\\n\x18org.chainmaker.pb.commonB\x15\x43hainmakerTransactionZ)chainmaker.org/chainmaker/pb-go/v3/commonb\x06proto3')



_TRANSACTION = DESCRIPTOR.message_types_by_name['Transaction']
_TRANSACTIONINFO = DESCRIPTOR.message_types_by_name['TransactionInfo']
_TRANSACTIONWITHRWSET = DESCRIPTOR.message_types_by_name['TransactionWithRWSet']
_TRANSACTIONINFOWITHRWSET = DESCRIPTOR.message_types_by_name['TransactionInfoWithRWSet']
Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'chainmaker.protos.common.transaction_pb2'
  # @@protoc_insertion_point(class_scope:common.Transaction)
  })
_sym_db.RegisterMessage(Transaction)

TransactionInfo = _reflection.GeneratedProtocolMessageType('TransactionInfo', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONINFO,
  '__module__' : 'chainmaker.protos.common.transaction_pb2'
  # @@protoc_insertion_point(class_scope:common.TransactionInfo)
  })
_sym_db.RegisterMessage(TransactionInfo)

TransactionWithRWSet = _reflection.GeneratedProtocolMessageType('TransactionWithRWSet', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONWITHRWSET,
  '__module__' : 'chainmaker.protos.common.transaction_pb2'
  # @@protoc_insertion_point(class_scope:common.TransactionWithRWSet)
  })
_sym_db.RegisterMessage(TransactionWithRWSet)

TransactionInfoWithRWSet = _reflection.GeneratedProtocolMessageType('TransactionInfoWithRWSet', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONINFOWITHRWSET,
  '__module__' : 'chainmaker.protos.common.transaction_pb2'
  # @@protoc_insertion_point(class_scope:common.TransactionInfoWithRWSet)
  })
_sym_db.RegisterMessage(TransactionInfoWithRWSet)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.chainmaker.pb.commonB\025ChainmakerTransactionZ)chainmaker.org/chainmaker/pb-go/v3/common'
  _TRANSACTION._serialized_start=172
  _TRANSACTION._serialized_end=379
  _TRANSACTIONINFO._serialized_start=382
  _TRANSACTIONINFO._serialized_end=526
  _TRANSACTIONWITHRWSET._serialized_start=528
  _TRANSACTIONWITHRWSET._serialized_end=625
  _TRANSACTIONINFOWITHRWSET._serialized_start=628
  _TRANSACTIONINFOWITHRWSET._serialized_end=814
# @@protoc_insertion_point(module_scope)
