/*
 * Interface wrapper code.
 *
 * Generated by SIP 6.7.12
 *
 *     
 */

#include "sipAPI_core.h"

        #include <wx/dcclient.h>
    #line 14 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"

        #include <wx/window.h>
    #line 18 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
    #include <wx/setup.h>
    #include "wxpy_api.h"
    #line 22 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/gdicmn.h>
    #line 25 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/graphics.h>
    #line 28 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/bitmap.h>
    #line 31 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/gdicmn.h>
    #line 34 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/palette.h>
    #line 37 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/colour.h>
    #line 40 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/gdicmn.h>
    #line 43 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/dc.h>
    #line 46 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/affinematrix2d.h>
    #line 49 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/pen.h>
    #line 203 "C:\\Users\\stephan\\Desktop\\wxPython-zombie\\sip\\gen\\pen.sip"
        #include "arrayholder.h"
    #line 54 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/brush.h>
    #line 57 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/font.h>
    #line 60 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/dc.h>
    #line 63 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/region.h>
    #line 66 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        
        
    #line 70 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/icon.h>
    #line 73 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/object.h>
    #line 76 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/object.h>
    #line 79 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"
        #include <wx/object.h>
    #line 82 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"


class sipwxClientDC : public ::wxClientDC
{
public:
    sipwxClientDC(::wxWindow*);
    ~sipwxClientDC();

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipwxClientDC(const sipwxClientDC &);
    sipwxClientDC &operator = (const sipwxClientDC &);
};

sipwxClientDC::sipwxClientDC(::wxWindow*window): ::wxClientDC(window), sipPySelf(SIP_NULLPTR)
{
}

sipwxClientDC::~sipwxClientDC()
{
    sipInstanceDestroyedEx(&sipPySelf);
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_wxClientDC(void *, const sipTypeDef *);}
static void *cast_wxClientDC(void *sipCppV, const sipTypeDef *targetType)
{
    ::wxClientDC *sipCpp = reinterpret_cast<::wxClientDC *>(sipCppV);

    if (targetType == sipType_wxClientDC)
        return sipCppV;

    sipCppV = ((const sipClassTypeDef *)sipType_wxWindowDC)->ctd_cast(static_cast<::wxWindowDC *>(sipCpp), targetType);
    if (sipCppV)
        return sipCppV;

    return SIP_NULLPTR;
}


/* Call the instance's destructor. */
extern "C" {static void release_wxClientDC(void *, int);}
static void release_wxClientDC(void *sipCppV, int sipState)
{
    Py_BEGIN_ALLOW_THREADS

    if (sipState & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipwxClientDC *>(sipCppV);
    else
        delete reinterpret_cast<::wxClientDC *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_wxClientDC(sipSimpleWrapper *);}
static void dealloc_wxClientDC(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipwxClientDC *>(sipGetAddress(sipSelf))->sipPySelf = SIP_NULLPTR;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_wxClientDC(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_wxClientDC(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_wxClientDC(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipwxClientDC *sipCpp = SIP_NULLPTR;

    {
        ::wxWindow* window;

        static const char *sipKwdList[] = {
            sipName_window,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "J8", sipType_wxWindow, &window))
        {

        if (!wxPyCheckForApp()) return NULL;
    #line 171 "C:\\Users\\stephan\\AppData\\Local\\Temp\\tmpa4fufw9u\\build\\_core/sip_corewxClientDC.cpp"

            PyErr_Clear();

            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipwxClientDC(window);
            Py_END_ALLOW_THREADS

            if (PyErr_Occurred())
            {
                delete sipCpp;
                return SIP_NULLPTR;
            }

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return SIP_NULLPTR;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_wxClientDC[] = {{612, 255, 1}};

PyDoc_STRVAR(doc_wxClientDC, "ClientDC(window)\n"
"\n"
"wxClientDC is primarily useful for obtaining information about the\n"
"window from outside EVT_PAINT() handler.");


sipClassTypeDef sipTypeDef__core_wxClientDC = {
    {
        -1,
        SIP_NULLPTR,
        SIP_NULLPTR,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_wxClientDC,
        SIP_NULLPTR,
        SIP_NULLPTR,
    },
    {
        sipNameNr_ClientDC,
        {0, 0, 1},
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        0, SIP_NULLPTR,
        {SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR, SIP_NULLPTR},
    },
    doc_wxClientDC,
    -1,
    -1,
    supers_wxClientDC,
    SIP_NULLPTR,
    init_type_wxClientDC,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    dealloc_wxClientDC,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    release_wxClientDC,
    cast_wxClientDC,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    SIP_NULLPTR,
    sizeof (::wxClientDC),
};
