
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-27T14:53:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe2ee0f19cd40616a5f8435a45a40a4fe46f25d0",
 "version": "1.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
