from setuptools import setup, find_packages

setup(
    name = 'blockmetro',
    packages = find_packages(),
    version = '1.1',
    lisense = 'MIT',
    description = 'Python bindings for the BlockMetro API',
    author = 'BlockMetro',
    author_email = 'support@blockmetro.io',
    url = 'https://github.com/BlockMetro/blockmetro-python',
    download_url = 'https://github.com/BlockMetro/blockmetro-python',
    keywords = ['cardano', 'api'],
    python_requires = ">=3.6",
    classifiers = [
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
