"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.ats
from MergePythonSDK.shared.model.remote_data import RemoteData
from MergePythonSDK.ats.model.scheduled_interview_status_enum import ScheduledInterviewStatusEnum
globals()['RemoteData'] = RemoteData
globals()['ScheduledInterviewStatusEnum'] = ScheduledInterviewStatusEnum
from MergePythonSDK.ats.model.scheduled_interview import ScheduledInterview
from MergePythonSDK.shared.api_client import ApiClient


class TestScheduledInterview(unittest.TestCase):
    """ScheduledInterview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduledInterview(self):
        """Test ScheduledInterview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScheduledInterview()  # noqa: E501

        """
        No test json responses were defined for ScheduledInterview
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (ScheduledInterview,), False)

        assert deserialized is not None



if __name__ == '__main__':
    unittest.main()
