def test(val):
    print(val,"-->",g.rank(val)," | ",g.label(g.rank(val)))

g = RangeSet(1,2,5)
print("RangeSet(1,2,5)")
print(g.ranges.items())
print("min :",g.min_rank())
print("max :",g.max_rank())
test(3)
test(12)
test(1)
test(4)
test(1.5)
print()
g = RangeSet(1,(2,4),5,6,7,(7,9),11)
print("RangeSet(1,(2,4),5,6,7,(7,9),11)")
print(g.ranges.items())
print(g)
print("min :",g.min_rank())
print("max :",g.max_rank())
test(3)
test(12)
test(1)
test(4)
test(1.5)
test(7)
test(7.5)
test(10)
print()
g = RangeSet((0,1),(2,3),(3,5))
print("RangeSet((0,1),(2,3),(3,5))")
print(g.ranges.items())
test(1.5)
test(2)
test(-1)
test(3)
test(3.5)
test(12)
print()
g = RangeSet([0,1],[2,3],[3,5])
print("RangeSet([0,1],[2,3],[3,5])")
print(g.ranges.items())
print(g)
test(1.5)
test(15)
print()
# Exemples qui génèrent une exception :
#g = RangeSet() 
#g = RangeSet(())
#g = RangeSet((0,1),(6,3),(3,5))
#g = RangeSet((0,1),(2,4),(3,5))
g = RangeSet(6,3,5)