
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-26T14:10:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8dddc2db49fcafee1e044ad3e74f96687ce113fb",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
