# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from perian.models.gpu_creation_success import GPUCreationSuccess  # noqa: E501

class TestGPUCreationSuccess(unittest.TestCase):
    """GPUCreationSuccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GPUCreationSuccess:
        """Test GPUCreationSuccess
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GPUCreationSuccess`
        """
        model = GPUCreationSuccess()  # noqa: E501
        if include_optional:
            return GPUCreationSuccess(
                status = 'success',
                message = 'RegisteredGPU created successful',
                detail = '',
                status_code = 56
            )
        else:
            return GPUCreationSuccess(
        )
        """

    def testGPUCreationSuccess(self):
        """Test GPUCreationSuccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
