# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from perian.models.flavor_blocked_error import FlavorBlockedError  # noqa: E501

class TestFlavorBlockedError(unittest.TestCase):
    """FlavorBlockedError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlavorBlockedError:
        """Test FlavorBlockedError
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlavorBlockedError`
        """
        model = FlavorBlockedError()  # noqa: E501
        if include_optional:
            return FlavorBlockedError(
                status = 'error',
                message = 'Operation was not successful',
                detail = 'The selected flavor type is blocked for your account',
                status_code = 56
            )
        else:
            return FlavorBlockedError(
        )
        """

    def testFlavorBlockedError(self):
        """Test FlavorBlockedError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
