from kamutils.analyse import RangeSet

def test(val):
    print(val,"-->",g.level(val)," | ",g.label(g.level(val)))

g = RangeSet(1,2,5)
print("RangeSet(1,2,5)")
print(g)
# La boucle ci-dessous permet aussi de tester l'absence de conflit de nom avec la fonction range() standard
print([(i,g.label(i)) for i in range(0,len(g))])
print("last level :",g.last_level())
test(3)
test(12)
test(1)
test(4)
test(1.5)
print()
g = RangeSet(1,(2,4),5,6,7,(7,9),11)
print("RangeSet(1,(2,4),5,6,7,(7,9),11)")
print(g)
print([(i,g.label(i)) for i in range(0,len(g))])
print("last level :",g.last_level())
test(3)
test(12)
test(1)
test(4)
test(1.5)
test(7)
test(7.5)
test(10)
print()
g = RangeSet((0,1),(2,3),(3,5))
print("RangeSet((0,1),(2,3),(3,5))")
print(g)
print([(i,g.label(i)) for i in range(0,len(g))])
print("last level :",g.last_level())
test(1.5)
test(2)
test(-1)
test(3)
test(3.5)
test(12)
print()
g = RangeSet([0,1],[2,3],[3,5])
print("RangeSet([0,1],[2,3],[3,5])")
print(g)
print([(i,g.label(i)) for i in range(0,len(g))])
print(g)
test(1.5)
test(15)
print()
# Exemples qui génèrent une exception :
#g = RangeSet() 
#g = RangeSet(())
#g = RangeSet((0,1),(6,3),(3,5))
#g = RangeSet((0,1),(2,4),(3,5))
g = RangeSet(6,3,5)