
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-10-25T09:48:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2dd28ef1ecd27f1db08b0d2cb33ee27fd2136ec",
 "version": "0.7.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
