"""
    Merge Accounting API

    The unified API for building rich integrations with multiple Accounting & Finance platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.accounting
from MergePythonSDK.accounting.model.state_enum import StateEnum
from MergePythonSDK.shared.api_client import ApiClient


class TestStateEnum(unittest.TestCase):
    """StateEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateEnum(self):
        """Test StateEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StateEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
