"""
    Merge Accounting API

    The unified API for building rich integrations with multiple Accounting & Finance platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergePythonSDK.accounting
from MergePythonSDK.accounting.model.contact import Contact
from MergePythonSDK.accounting.model.debug_mode_log import DebugModeLog
from MergePythonSDK.accounting.model.error_validation_problem import ErrorValidationProblem
from MergePythonSDK.accounting.model.warning_validation_problem import WarningValidationProblem
globals()['Contact'] = Contact
globals()['DebugModeLog'] = DebugModeLog
globals()['ErrorValidationProblem'] = ErrorValidationProblem
globals()['WarningValidationProblem'] = WarningValidationProblem
from MergePythonSDK.accounting.model.contact_response import ContactResponse
from MergePythonSDK.shared.api_client import ApiClient


class TestContactResponse(unittest.TestCase):
    """ContactResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactResponse(self):
        """Test ContactResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ContactResponse()  # noqa: E501

        """
        No test json responses were defined for ContactResponse
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (ContactResponse,), False)

        assert deserialized is not None

        assert deserialized.model is not None
        assert deserialized.warnings is not None
        assert deserialized.errors is not None


if __name__ == '__main__':
    unittest.main()
